# Generated by Django 3.1.7 on 2021-03-07 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corretora',
            options={'ordering': ['name'], 'verbose_name_plural': 'corretoras'},
        ),
        migrations.AlterModelOptions(
            name='favoritestock',
            options={'ordering': ['auth_user_id'], 'verbose_name_plural': 'favoritestocks'},
        ),
        migrations.AlterModelOptions(
            name='investorprofile',
            options={'verbose_name_plural': 'investorprofiles'},
        ),
        migrations.AlterModelOptions(
            name='modelcandidatevote',
            options={'ordering': ['auth_user_id'], 'verbose_name_plural': 'modelcandidatevotes'},
        ),
        migrations.AlterModelOptions(
            name='models',
            options={'ordering': ['name'], 'verbose_name_plural': 'models'},
        ),
        migrations.AlterModelOptions(
            name='profiletype',
            options={'ordering': ['name'], 'verbose_name_plural': 'profiletypes'},
        ),
        migrations.AlterModelOptions(
            name='stockradar',
            options={'ordering': ['name'], 'verbose_name_plural': 'stocksradar'},
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='auth_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='r1',
            field=models.IntegerField(choices=[('0', ''), ('1', 'Preservar meu patrimônio assumindo um risco menor.'), ('2', 'Uma combinação entre preservação do meu patrimônio e sua valorização.'), ('3', 'Maximizar o potencial de ganho assumindo um risco maior.')], default=0, verbose_name='Qual a principal finalidade de investir seu patrimônio conosco?'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='r10',
            field=models.IntegerField(choices=[('0', ''), ('1', 'Até R$ 20.000,00.'), ('2', 'Entre R$ 20.000,01 e R$ 100.000,00.'), ('3', 'Entre R$ 100.000,01 a R$ 1.000.000,00.'), ('4', 'Acima de R$ 1.000.000,01.')], default=0, verbose_name='Qual é o valor do seu Patrimônio?'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='r11',
            field=models.IntegerField(choices=[('0', ''), ('1', 'Não tenho formação acadêmica na área financeira, mas desejo operar no mercado de capitais e financeiro.'), ('2', 'Apesar de não ter a formação acadêmica na área financeira possuo experiência no mercado de capitais e financeiro.'), ('3', 'Tenho formação na área financeira e conheço as regras do mercado financeiro.'), ('4', 'Tenho formação acadêmica e experiência profissional na área financeira, por isto conheço profundamente o mercado financeiro, como operações de derivativos e estruturadas.')], default=0, verbose_name='Como você classificaria a relação de sua formação acadêmica e da sua experiência profissional em relação aos seus conhecimentos sobre o mercado financeiro?'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='r12',
            field=models.IntegerField(choices=[('1', 'Não admito perder nada do capital investido. Procuro um retorno seguro e sem oscilações. Segurança é mais importante do que rentabilidade.'), ('2', 'Não admito perder nada do capital investido, no entanto posso arriscar uma parte do capital para alcançar resultados melhores que a renda fixa tradicional. Valorizo mais a segurança do que a rentabilidade.'), ('3', 'Posso correr riscos para conseguir uma rentabilidade acima da média, no entanto, prezo a preservação de 100% do capital investido. Divido minhas preferências entre segurança e rentabilidade, mas ainda prefiro segurança à rentabilidade..'), ('4', 'Admito perdas de até 20% do capital investido, se a proposta de investimento gerar possibilidade de altos retornos. A procura por rentabilidade é mais importante do que a segurança.'), ('5', 'Minha prioridade é maximizar a rentabilidade, com a segurança em segundo plano. Posso correr grande riscos para obter elevados retornos, admitindo perder mais de 20% do meu capital investido.')], default=0, verbose_name='Qual das respostas abaixo mais se assemelha à sua personalidade como investidor?'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='r2',
            field=models.IntegerField(choices=[('0', ''), ('1', 'Até 1 ano.'), ('2', '1 a 5 anos.'), ('3', 'Mais de 5 anos.'), ('4', 'Essa reserva não será utilizada, a não ser em caso de emergência.')], default=0, verbose_name='Por quanto tempo pretende deixar seus recursos investidos conosco?'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='r3',
            field=models.IntegerField(choices=[('0', ''), ('1', 'Preciso desse dinheiro como complemento de renda .'), ('2', 'Eventualmente posso precisar utilizar uma parte dele.'), ('3', 'Não tenho necessidade imediata desse dinheiro')], default=0, verbose_name='Em relação aos seus investimentos na SLW, qual é a necessidade futura dos recursos aplicados?'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='r4',
            field=models.IntegerField(choices=[('0', ''), ('1', 'Até R$ 3.000,00'), ('2', 'Entre R$ 3.000,00 e R$ 5.000,00.'), ('3', 'Entre R$ 5.000,00 e R$ 10.000,00.'), ('4', 'Entre R$ 10.000,00 e R$ 30.000,00.'), ('5', 'Mais de R$ 30.000,00.')], default=0, verbose_name='Qual a sua renda mensal?'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='r5',
            field=models.IntegerField(choices=[('0', ''), ('1', 'Até 10%.'), ('2', 'De 10 a 20%.'), ('3', 'De 20% a 50%.'), ('4', 'Acima de 50%.')], default=0, verbose_name='Qual percentual da sua renda o (a) Sr.(a) investe regularmente?'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='r6',
            field=models.IntegerField(choices=[('0', ''), ('1', 'Não sei o que faria.'), ('2', 'Venderia toda a posição.'), ('3', 'Manteria a posição.'), ('4', 'Aumentaria a posição.')], default=0, verbose_name='Por conta de oscilações do mercado, considere que seus investimentos percam 10% do valor aplicado. Neste caso, o que o (a) Sr.(a) faria?'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='r7',
            field=models.IntegerField(choices=[('0', ''), ('1', 'Poupança, Fundos DI, CDB, Fundos de Renda Fixa.'), ('2', 'Fundos Multimercados, Títulos Públicos, LCI, LCA.'), ('3', ' Fundos de Ações, Ações, Fundos Imobiliários, Debêntures, Fundos Cambiais, Clubes de Investimento.'), ('4', 'Fundos de Investimentos em Participações (FIP), Derivativos (Futuros, Opções e Swaps).')], default=0, verbose_name='Quais dos produtos listados abaixo você tem familiaridade? (Esta questão permite múltiplas respostas. Para fins de cálculo de Perfil, deve ser utilizada a resposta de maior valor de pontuação entre as respostas assinaladas).'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='r8',
            field=models.IntegerField(choices=[('0', ''), ('1', 'Preservar meu patrimônio assumindo um risco menor.'), ('2', 'Uma combinação entre preservação do meu patrimônio e sua valorização.'), ('3', 'Maximizar o potencial de ganho assumindo um risco maior.')], default=0, verbose_name='Quais investimentos você realizou frequentemente nos últimos 24 meses?'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='r9',
            field=models.IntegerField(choices=[('0', ''), ('1', 'Renda Variável (Ações e Fundos de Ações).'), ('2', 'Fundos de Investimento Multimercado.'), ('3', 'Renda Fixa (Fundos de Renda Fixa, DI, CDBs, Poupança).'), ('4', 'Imóveis.'), ('5', 'Outros.')], default=0, verbose_name='Qual é a atual composição dos seus investimentos por categoria? (Esta questão permite múltiplas respostas. Para fins de cálculo do Perfil, deve ser utilizada a resposta com o maior percentual e no caso de respostas com porcentagens iguais, deve ser utilizada a resposta mais conservadora).'),
        ),
    ]
