# Generated by Django 3.1.7 on 2021-03-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20210307_1259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Corretora',
            new_name='Broker',
        ),
        migrations.AlterModelOptions(
            name='broker',
            options={'ordering': ['name'], 'verbose_name_plural': 'Brokers'},
        ),
        migrations.AlterModelOptions(
            name='favoritestock',
            options={'ordering': ['auth_user_id'], 'verbose_name_plural': 'Favorite Stocks'},
        ),
        migrations.AlterModelOptions(
            name='investorprofile',
            options={'verbose_name_plural': 'Investor Profiles'},
        ),
        migrations.AlterModelOptions(
            name='modelcandidatevote',
            options={'ordering': ['auth_user_id'], 'verbose_name_plural': 'Model Candidate Votes'},
        ),
        migrations.AlterModelOptions(
            name='models',
            options={'ordering': ['name'], 'verbose_name_plural': 'Models'},
        ),
        migrations.AlterModelOptions(
            name='profiletype',
            options={'ordering': ['name'], 'verbose_name_plural': 'Profile Types'},
        ),
        migrations.AlterModelOptions(
            name='stockradar',
            options={'ordering': ['name'], 'verbose_name_plural': 'Stocks Radar'},
        ),
        migrations.RenameField(
            model_name='investorprofile',
            old_name='corretora_id',
            new_name='broker_id',
        ),
    ]
