# Generated by Django 3.1.7 on 2021-03-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('landing', '0004_authuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockradar',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
