# Generated by Django 3.1.7 on 2021-03-12 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20210312_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelinvestmentportfolio',
            options={'verbose_name_plural': 'Investor Portifolio'},
        ),
    ]
