# Generated by Django 3.1.7 on 2021-03-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20210312_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelinvestmentportfolio',
            name='has_in_portifolio',
        ),
    ]
