# Generated by Django 3.1.7 on 2021-03-06 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('confidence', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StockRadar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModelCandidateVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stock_radar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingbitpy.stockradar')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.IntegerField(default=0)),
                ('r2', models.IntegerField(default=0)),
                ('r3', models.IntegerField(default=0)),
                ('r4', models.IntegerField(default=0)),
                ('r5', models.IntegerField(default=0)),
                ('r6', models.IntegerField(default=0)),
                ('r7', models.IntegerField(default=0)),
                ('r8', models.IntegerField(default=0)),
                ('r9', models.IntegerField(default=0)),
                ('r10', models.IntegerField(default=0)),
                ('r11', models.IntegerField(default=0)),
                ('r12', models.IntegerField(default=0)),
                ('corretora', models.CharField(max_length=10)),
                ('profiletype', models.CharField(max_length=10)),
                ('auth_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stock_radar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingbitpy.stockradar')),
            ],
        ),
    ]
